import { createNewCart, generateId } from './components/helpers';

//// LOCAL STORAGE  ///////////////
export const cart = {
  order: {
    id: generateId(9),
    user_id: null,
    total_price: 0,
    status: 'unshipped',
    delivery: null,
    date: null,
  },
  items: [],
};

export const categories = new Map([
  [
    'Clothes',

    [
      { subCatName: `Men's`, img: './images/men_clothes.jpg' },
      { subCatName: `Women's`, img: './images/women_clothes.jpg' },
      { subCatName: `Men's / Women's`, img: './images/women_clothes.jpg' },
    ],
  ],
  [
    'Shoes',
    [
      { subCatName: `Men's`, img: './images/men_shoe.jpg' },
      { subCatName: `Women's`, img: './images/women_shoe.jpg' },
      { subCatName: `Men's / Women's`, img: './images/women_shoe.jpg' },
    ],
  ],
  [
    'Watchs',
    [
      { subCatName: `Men's`, img: './images/men_watch.jpg' },
      { subCatName: `Women's`, img: './images/women_watch.jpg' },
      { subCatName: `Men's / Women's`, img: './images/women_watch.jpg' },
    ],
  ],
  [
    'Jewelries',
    [
      { subCatName: `Men's`, img: './images/men_jew.jpg' },
      { subCatName: `Women's`, img: './images/women_jew.jpg' },
      { subCatName: `Men's / Women's`, img: './images/women_jew.jpg' },
    ],
  ],
  [
    'Decor kits',
    [
      { subCatName: 'Light strip', img: './images/room_light.jpg' },
      { subCatName: 'Bright form', img: './images/lightening_butterflies.jpg' },
    ],
  ],
  [
    'Multimedia kits',
    [
      { subCatName: 'Airpods', img: './images/airpods.jpg' },
      { subCatName: 'Headphone', img: './images/headphone.jpg' },
      { subCatName: 'Powerbank', img: './images/powerbank.jpg' },
      { subCatName: 'Phone charger', img: './images/phone_charger.jpg' },
    ],
  ],
]);

export const advantagesInfos = [
  {
    title: 'Free delivery',
    imgUrl: 'free-truck.png',
    text: 'Free delivery every Saturday and from a cerain amount, we offer free delivery.',
  },
  {
    title: 'Welcome discount',
    imgUrl: '10%-off.png',
    text: '10% off on your first order.',
  },
  {
    title: 'Loyality program',
    imgUrl: 'loyalty.png',
    text: 'Point can be accumulated with each purchase. From a certain number of points, you either get a gift or a discount.',
  },
  {
    title: 'Limited offer / Flash sales',
    imgUrl: 'flash-sales.png',
    text: 'We can reduce the price of certain items by up to 20% for a limited period.',
  },
  {
    title: 'Sponsorship discount',
    imgUrl: 'sponsor.png',
    text: 'Refer your friends and get your bonuses.',
  },
];
//// LOCAL STORAGE ///////////////

//--------------------------------//

//// DATA BASE ///////////////
export const products = [
  {
    id: 'qqd2',
    product_name: 'Costume',
    product_price: '25000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Clothes',
    sub_category: `Men's`,
    stock: 5,
    sales: 10,
    date_mod: '2025-10-07T15:25:31.137Z',
  },
  {
    id: '2bgn2',
    product_name: 'Jean Trouser',
    product_price: '7000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Clothes',
    sub_category: `Men's`,
    stock: 30,
    sales: 13,
    date_mod: '2025-10-07T15:28:20.137Z',
  },
  {
    id: 'ty34',
    product_name: 'Kaba',
    product_price: '10000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Clothes',
    sub_category: `Women's`,
    stock: 25,
    sales: 12,
    date_mod: '2025-12-21T16:28:20.137Z',
  },
  {
    id: 'ddfg3',
    product_name: 'Shirt',
    product_price: '5000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Clothes',
    sub_category: `Men's`,
    stock: 50,
    sales: 2,
    date_mod: '2025-12-21T11:23:20.137Z',
  },
  {
    id: 'gfg4',
    product_name: 'Skirt',
    product_price: '2000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Clothes',
    sub_category: `Women's`,
    stock: 48,
    sales: 13,
    date_mod: '2025-12-07T15:28:20.137Z',
  },
  {
    id: 'gfh96',
    product_name: 'Ballerina',
    product_price: '7000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Shoes',
    sub_category: `Women's`,
    stock: 40,
    sales: 3,
    date_mod: '2025-12-07T15:26:20.137Z',
  },
  {
    id: 'kj90',
    product_name: 'Balenciaga',
    product_price: '15000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Shoes',
    sub_category: `Men's`,
    stock: 6,
    sales: 13,
    date_mod: '2025-11-30T17:28:20.137Z',
  },
  {
    id: 'llkk8',
    product_name: 'Air nike',
    product_price: '20000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Shoes',
    sub_category: `Men's`,
    stock: 3,
    sales: 15,
    date_mod: '2025-11-30T17:40:20.137Z',
  },
  {
    id: 'hguyt8',
    product_name: 'Prada',
    product_price: '15000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Shoes',
    sub_category: `Men's`,
    stock: 5,
    sales: 15,
    date_mod: '2025-11-30T17:50:02.137Z',
  },
  {
    id: 'xz2',
    product_name: 'New balance',
    product_price: '17000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Shoes',
    sub_category: `Women's`,
    stock: 33,
    sales: 1,
    date_mod: '2025-12-04T11:40:17.137Z',
  },

  {
    id: 'dd5',
    product_name: 'Cartier',
    product_price: '15000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Watchs',
    sub_category: `Women's`,
    stock: 8,
    sales: 5,
    date_mod: '2025-12-04T11:50:36.137Z',
  },
  {
    id: 'hp53fd42',
    product_name: 'TAG Heuer',
    product_price: '7000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Watchs',
    sub_category: `Women's`,
    stock: 14,
    sales: 0,
    date_mod: '2025-12-22T10:50:36.137Z',
  },
  {
    id: 'zvg7',
    product_name: 'Omega',
    product_price: '7000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Watchs',
    sub_category: `Women's`,
    stock: 18,
    sales: 3,
    date_mod: '2025-12-04T12:02:36.137Z',
  },
  {
    id: 'k;0-',
    product_name: 'Rolex',
    product_price: '5000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Watchs',
    sub_category: `Men's`,
    stock: 0,
    sales: 25,
    date_mod: '2025-09-04T12:35:36.137Z',
  },
  {
    id: 'hgnhg0',
    product_name: 'Rolex XMD',
    product_price: '12000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Watchs',
    sub_category: `Men's`,
    stock: 1,
    sales: 45,
    date_mod: '2025-08-24T06:10:02.137Z',
  },
  {
    id: 'dduh475',
    product_name: 'Rings',
    product_price: '1000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Jewelries',
    sub_category: `Women's`,
    stock: 38,
    sales: 18,
    date_mod: '2025-12-21T10:50:06.137Z',
  },
  {
    id: 'hgkl542',
    product_name: 'Brooches',
    product_price: '2000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Jewelries',
    sub_category: `Men's`,
    stock: 11,
    sales: 12,
    date_mod: '2025-11-04T15:10:36.137Z',
  },
  {
    id: 'zvwe78g7',
    product_name: 'Necklaces',
    product_price: '1500 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Jewelries',
    sub_category: `Women's`,
    stock: 0,
    sales: 55,
    date_mod: '2025-08-04T11:19:39.137Z',
  },
  {
    id: 'k;0hy5785',
    product_name: 'Anklets',
    product_price: '2000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Jewelries',
    sub_category: `Women's`,
    stock: 1,
    sales: 18,
    date_mod: '2025-12-04T11:00:36.137Z',
  },
  {
    id: 'hgnhd78g0',
    product_name: 'Bracelet',
    product_price: '800 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Jewelries',
    sub_category: `Men's`,
    stock: 58,
    sales: 0,
    date_mod: '2025-12-21T11:50:36.137Z',
  },
  {
    id: 'hghjgf7',
    product_name: 'Multipurpose light strip',
    product_price: '3000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Decor kits',
    sub_category: 'Light strip',
    stock: 2,
    sales: 55,
    date_mod: '2025-12-04T16:03:36.137Z',
  },
  {
    id: 'gfgfd5',
    product_name: 'Bedroom light strip',
    product_price: '5000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Decor kits',
    sub_category: 'Light strip',
    stock: 50,
    sales: 5,
    date_mod: '2025-12-23T16:25:01.137Z',
  },
  {
    id: 'gfj9',
    product_name: 'Office ligth dec',
    product_price: '2000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Decor kits',
    sub_category: 'Light strip',
    stock: 60,
    sales: 1,
    date_mod: '2025-12-23T22:50:45.137Z',
  },
  {
    id: 'gfhg554',
    product_name: 'Decor light',
    product_price: '2500 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Decor kits',
    sub_category: 'Bright form',
    stock: 36,
    sales: 3,
    date_mod: '2025-12-24T11:50:36.137Z',
  },
  {
    id: 'hj-9',
    product_name: 'Butterflies light',
    product_price: '8000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Decor kits',
    sub_category: 'Bright form',
    stock: 54,
    sales: 1,
    date_mod: '2025-12-24T11:58:06.137Z',
  },
  {
    id: 'fddhjh07',
    product_name: 'Airpods BL9',
    product_price: '7000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Multimedia kits',
    sub_category: 'Airpods',
    stock: 5,
    sales: 25,
    date_mod: '2025-08-04T11:17:36.137Z',
  },
  {
    id: '559hgf',
    product_name: 'LAUD headphone',
    product_price: '8000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Multimedia kits',
    sub_category: 'Headphone',
    stock: 8,
    sales: 12,
    date_mod: '2025-09-10T19:50:27.137Z',
  },
  {
    id: 'fhm90',
    product_name: 'Oraimo charger',
    product_price: '5000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Multimedia kits',
    sub_category: 'Phone charger',
    stock: 0,
    sales: 35,
    date_mod: '2025-11-04T14:38:36.137Z',
  },
  {
    id: '656huy',
    product_name: 'Oraimo Long lasting power Bank',
    product_price: '20000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Multimedia kits',
    sub_category: 'Powerbank',
    stock: 23,
    sales: 2,
    date_mod: '2025-09-04T16:32:06.137Z',
  },
  {
    id: '8776hgh',
    product_name: 'Sony XVL',
    product_price: '5000 XAF',
    isLiked: false,
    img_url: '/head-img.jpg',
    category: 'Multimedia kits',
    sub_category: 'Headphone',
    stock: 27,
    sales: 8,
    date_mod: '2025-08-21T13:51:09.137Z',
  },
];

export const accounts = [
  {
    id: 'qw52sblo',
    username: 'Admin',
    email: 'admin@iyaksarl.com',
    password: '12345678',
    role: 'admin',
  },
];

export const orders = [];

export const orderItems = [];
//// DATA BASE ///////////////
