const articlesData = [
  {
    name: 'Clothes',
    cards: [
      {
        id: 'qqd2',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'gn2',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'ty34',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'ddfg3',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'gfg4',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
    ],
  },
  {
    name: 'Shoes',
    cards: [
      {
        id: 'gfh96',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'kj90',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'llkk8',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'hguyt8',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'xz2',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
    ],
  },
  {
    name: 'Watchs',
    cards: [
      {
        id: 'dd5',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'hgkl542',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'zvg7',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'k;0-',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'hgnhg0',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
    ],
  },
  {
    name: 'Jewelry',
    cards: [
      {
        id: 'dd5',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'hgkl542',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'zvg7',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'k;0-',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'hgnhg0',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
    ],
  },
  {
    name: 'Decoration gadgets',
    cards: [
      {
        id: 'hghjgf7',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'gfgfd5',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'gfj9',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'gfhg554',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'hj-9',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
    ],
  },
  {
    name: 'Multimedia kits',
    cards: [
      {
        id: 'fddhjh07',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: '559hgf',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: 'fhm90',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: '656huy',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
      {
        id: '8776hgh',
        product_name: '',
        product_price: '',
        isLiked: false,
        img_url: 'head-img.jpg',
      },
    ],
  },
];
export default articlesData;
